// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohkgjmyynpoibjrszpci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oa2dqbXl5bnBvaWJqcnN6cGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MTYwMDYsImV4cCI6MjA3NDQ5MjAwNn0.ubqhC27rsEuyC9YYmCCO8lRExEQ5EJWoU5NSkPhJHgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});